using System;

namespace SharpSDL
{
    public static unsafe partial class SDL
    {
        public const int SDLK_MASK = 1 << 30;
    }

    public enum Keycode
    {
        UNKNOWN = 0,

        RETURN = '\r',
        ESCAPE = 27,
        BACKSPACE = '\b',
        TAB = '\t',
        SPACE = ' ',
        EXCLAIM = '!',
        QUOTEDBL = '"',
        HASH = '#',
        PERCENT = '%',
        DOLLAR = '$',
        AMPERSAND = '&',
        QUOTE = '\'',
        LEFTPAREN = '(',
        RIGHTPAREN = ')',
        ASTERISK = '*',
        PLUS = '+',
        COMMA = ',',
        MINUS = '-',
        PERIOD = '.',
        SLASH = '/',
        N0 = '0',
        N1 = '1',
        N2 = '2',
        N3 = '3',
        N4 = '4',
        N5 = '5',
        N6 = '6',
        N7 = '7',
        N8 = '8',
        N9 = '9',
        COLON = ':',
        SEMICOLON = ';',
        LESS = '<',
        EQUALS = '=',
        GREATER = '>',
        QUESTION = '?',
        AT = '@',
        /*
           Skip uppercase letters
         */
        LEFTBRACKET = '[',
        BACKSLASH = '\\',
        RIGHTBRACKET = ']',
        CARET = '^',
        UNDERSCORE = '_',
        BACKQUOTE = '`',
        a = 'a',
        b = 'b',
        c = 'c',
        d = 'd',
        e = 'e',
        f = 'f',
        g = 'g',
        h = 'h',
        i = 'i',
        j = 'j',
        k = 'k',
        l = 'l',
        m = 'm',
        n = 'n',
        o = 'o',
        p = 'p',
        q = 'q',
        r = 'r',
        s = 's',
        t = 't',
        u = 'u',
        v = 'v',
        w = 'w',
        x = 'x',
        y = 'y',
        z = 'z',

        CAPSLOCK = Scancode.CAPSLOCK | SDL.SDLK_MASK,

        F1 = Scancode.F1 | SDL.SDLK_MASK,
        F2 = Scancode.F2 | SDL.SDLK_MASK,
        F3 = Scancode.F3 | SDL.SDLK_MASK,
        F4 = Scancode.F4 | SDL.SDLK_MASK,
        F5 = Scancode.F5 | SDL.SDLK_MASK,
        F6 = Scancode.F6 | SDL.SDLK_MASK,
        F7 = Scancode.F7 | SDL.SDLK_MASK,
        F8 = Scancode.F8 | SDL.SDLK_MASK,
        F9 = Scancode.F9 | SDL.SDLK_MASK,
        F10 = Scancode.F10 | SDL.SDLK_MASK,
        F11 = Scancode.F11 | SDL.SDLK_MASK,
        F12 = Scancode.F12 | SDL.SDLK_MASK,

        PRINTSCREEN = Scancode.PRINTSCREEN | SDL.SDLK_MASK,
        SCROLLLOCK = Scancode.SCROLLLOCK | SDL.SDLK_MASK,
        PAUSE = Scancode.PAUSE | SDL.SDLK_MASK,
        INSERT = Scancode.INSERT | SDL.SDLK_MASK,
        HOME = Scancode.HOME | SDL.SDLK_MASK,
        PAGEUP = Scancode.PAGEUP | SDL.SDLK_MASK,
        DELETE = 127,
        END = Scancode.END | SDL.SDLK_MASK,
        PAGEDOWN = Scancode.PAGEDOWN | SDL.SDLK_MASK,
        RIGHT = Scancode.RIGHT | SDL.SDLK_MASK,
        LEFT = Scancode.LEFT | SDL.SDLK_MASK,
        DOWN = Scancode.DOWN | SDL.SDLK_MASK,
        UP = Scancode.UP | SDL.SDLK_MASK,

        NUMLOCKCLEAR = Scancode.NUMLOCKCLEAR | SDL.SDLK_MASK,
        KP_DIVIDE = Scancode.KP_DIVIDE | SDL.SDLK_MASK,
        KP_MULTIPLY = Scancode.KP_MULTIPLY | SDL.SDLK_MASK,
        KP_MINUS = Scancode.KP_MINUS | SDL.SDLK_MASK,
        KP_PLUS = Scancode.KP_PLUS | SDL.SDLK_MASK,
        KP_ENTER = Scancode.KP_ENTER | SDL.SDLK_MASK,
        KP_1 = Scancode.KP_1 | SDL.SDLK_MASK,
        KP_2 = Scancode.KP_2 | SDL.SDLK_MASK,
        KP_3 = Scancode.KP_3 | SDL.SDLK_MASK,
        KP_4 = Scancode.KP_4 | SDL.SDLK_MASK,
        KP_5 = Scancode.KP_5 | SDL.SDLK_MASK,
        KP_6 = Scancode.KP_6 | SDL.SDLK_MASK,
        KP_7 = Scancode.KP_7 | SDL.SDLK_MASK,
        KP_8 = Scancode.KP_8 | SDL.SDLK_MASK,
        KP_9 = Scancode.KP_9 | SDL.SDLK_MASK,
        KP_0 = Scancode.KP_0 | SDL.SDLK_MASK,
        KP_PERIOD = Scancode.KP_PERIOD | SDL.SDLK_MASK,

        APPLICATION = Scancode.APPLICATION | SDL.SDLK_MASK,
        POWER = Scancode.POWER | SDL.SDLK_MASK,
        KP_EQUALS = Scancode.KP_EQUALS | SDL.SDLK_MASK,
        F13 = Scancode.F13 | SDL.SDLK_MASK,
        F14 = Scancode.F14 | SDL.SDLK_MASK,
        F15 = Scancode.F15 | SDL.SDLK_MASK,
        F16 = Scancode.F16 | SDL.SDLK_MASK,
        F17 = Scancode.F17 | SDL.SDLK_MASK,
        F18 = Scancode.F18 | SDL.SDLK_MASK,
        F19 = Scancode.F19 | SDL.SDLK_MASK,
        F20 = Scancode.F20 | SDL.SDLK_MASK,
        F21 = Scancode.F21 | SDL.SDLK_MASK,
        F22 = Scancode.F22 | SDL.SDLK_MASK,
        F23 = Scancode.F23 | SDL.SDLK_MASK,
        F24 = Scancode.F24 | SDL.SDLK_MASK,
        EXECUTE = Scancode.EXECUTE | SDL.SDLK_MASK,
        HELP = Scancode.HELP | SDL.SDLK_MASK,
        MENU = Scancode.MENU | SDL.SDLK_MASK,
        SELECT = Scancode.SELECT | SDL.SDLK_MASK,
        STOP = Scancode.STOP | SDL.SDLK_MASK,
        AGAIN = Scancode.AGAIN | SDL.SDLK_MASK,
        UNDO = Scancode.UNDO | SDL.SDLK_MASK,
        CUT = Scancode.CUT | SDL.SDLK_MASK,
        COPY = Scancode.COPY | SDL.SDLK_MASK,
        PASTE = Scancode.PASTE | SDL.SDLK_MASK,
        FIND = Scancode.FIND | SDL.SDLK_MASK,
        MUTE = Scancode.MUTE | SDL.SDLK_MASK,
        VOLUMEUP = Scancode.VOLUMEUP | SDL.SDLK_MASK,
        VOLUMEDOWN = Scancode.VOLUMEDOWN | SDL.SDLK_MASK,
        KP_COMMA = Scancode.KP_COMMA | SDL.SDLK_MASK,
        KP_EQUALSAS400 = Scancode.KP_EQUALSAS400 | SDL.SDLK_MASK,

        ALTERASE = Scancode.ALTERASE | SDL.SDLK_MASK,
        SYSREQ = Scancode.SYSREQ | SDL.SDLK_MASK,
        CANCEL = Scancode.CANCEL | SDL.SDLK_MASK,
        CLEAR = Scancode.CLEAR | SDL.SDLK_MASK,
        PRIOR = Scancode.PRIOR | SDL.SDLK_MASK,
        RETURN2 = Scancode.RETURN2 | SDL.SDLK_MASK,
        SEPARATOR = Scancode.SEPARATOR | SDL.SDLK_MASK,
        OUT = Scancode.OUT | SDL.SDLK_MASK,
        OPER = Scancode.OPER | SDL.SDLK_MASK,
        CLEARAGAIN = Scancode.CLEARAGAIN | SDL.SDLK_MASK,
        CRSEL = Scancode.CRSEL | SDL.SDLK_MASK,
        EXSEL = Scancode.EXSEL | SDL.SDLK_MASK,

        KP_00 = Scancode.KP_00 | SDL.SDLK_MASK,
        KP_000 = Scancode.KP_000 | SDL.SDLK_MASK,
        THOUSANDSSEPARATOR = Scancode.THOUSANDSSEPARATOR | SDL.SDLK_MASK,
        DECIMALSEPARATOR = Scancode.DECIMALSEPARATOR | SDL.SDLK_MASK,
        CURRENCYUNIT = Scancode.CURRENCYUNIT | SDL.SDLK_MASK,
        CURRENCYSUBUNIT = Scancode.CURRENCYSUBUNIT | SDL.SDLK_MASK,
        KP_LEFTPAREN = Scancode.KP_LEFTPAREN | SDL.SDLK_MASK,
        KP_RIGHTPAREN = Scancode.KP_RIGHTPAREN | SDL.SDLK_MASK,
        KP_LEFTBRACE = Scancode.KP_LEFTBRACE | SDL.SDLK_MASK,
        KP_RIGHTBRACE = Scancode.KP_RIGHTBRACE | SDL.SDLK_MASK,
        KP_TAB = Scancode.KP_TAB | SDL.SDLK_MASK,
        KP_BACKSPACE = Scancode.KP_BACKSPACE | SDL.SDLK_MASK,
        KP_A = Scancode.KP_A | SDL.SDLK_MASK,
        KP_B = Scancode.KP_B | SDL.SDLK_MASK,
        KP_C = Scancode.KP_C | SDL.SDLK_MASK,
        KP_D = Scancode.KP_D | SDL.SDLK_MASK,
        KP_E = Scancode.KP_E | SDL.SDLK_MASK,
        KP_F = Scancode.KP_F | SDL.SDLK_MASK,
        KP_XOR = Scancode.KP_XOR | SDL.SDLK_MASK,
        KP_POWER = Scancode.KP_POWER | SDL.SDLK_MASK,
        KP_PERCENT = Scancode.KP_PERCENT | SDL.SDLK_MASK,
        KP_LESS = Scancode.KP_LESS | SDL.SDLK_MASK,
        KP_GREATER = Scancode.KP_GREATER | SDL.SDLK_MASK,
        KP_AMPERSAND = Scancode.KP_AMPERSAND | SDL.SDLK_MASK,
        KP_DBLAMPERSAND = Scancode.KP_DBLAMPERSAND | SDL.SDLK_MASK,
        KP_VERTICALBAR = Scancode.KP_VERTICALBAR | SDL.SDLK_MASK,
        KP_DBLVERTICALBAR = Scancode.KP_DBLVERTICALBAR | SDL.SDLK_MASK,
        KP_COLON = Scancode.KP_COLON | SDL.SDLK_MASK,
        KP_HASH = Scancode.KP_HASH | SDL.SDLK_MASK,
        KP_SPACE = Scancode.KP_SPACE | SDL.SDLK_MASK,
        KP_AT = Scancode.KP_AT | SDL.SDLK_MASK,
        KP_EXCLAM = Scancode.KP_EXCLAM | SDL.SDLK_MASK,
        KP_MEMSTORE = Scancode.KP_MEMSTORE | SDL.SDLK_MASK,
        KP_MEMRECALL = Scancode.KP_MEMRECALL | SDL.SDLK_MASK,
        KP_MEMCLEAR = Scancode.KP_MEMCLEAR | SDL.SDLK_MASK,
        KP_MEMADD = Scancode.KP_MEMADD | SDL.SDLK_MASK,
        KP_MEMSUBTRACT = Scancode.KP_MEMSUBTRACT | SDL.SDLK_MASK,
        KP_MEMMULTIPLY = Scancode.KP_MEMMULTIPLY | SDL.SDLK_MASK,
        KP_MEMDIVIDE = Scancode.KP_MEMDIVIDE | SDL.SDLK_MASK,
        KP_PLUSMINUS = Scancode.KP_PLUSMINUS | SDL.SDLK_MASK,
        KP_CLEAR = Scancode.KP_CLEAR | SDL.SDLK_MASK,
        KP_CLEARENTRY = Scancode.KP_CLEARENTRY | SDL.SDLK_MASK,
        KP_BINARY = Scancode.KP_BINARY | SDL.SDLK_MASK,
        KP_OCTAL = Scancode.KP_OCTAL | SDL.SDLK_MASK,
        KP_DECIMAL = Scancode.KP_DECIMAL | SDL.SDLK_MASK,
        KP_HEXADECIMAL = Scancode.KP_HEXADECIMAL | SDL.SDLK_MASK,

        LCTRL = Scancode.LCTRL | SDL.SDLK_MASK,
        LSHIFT = Scancode.LSHIFT | SDL.SDLK_MASK,
        LALT = Scancode.LALT | SDL.SDLK_MASK,
        LGUI = Scancode.LGUI | SDL.SDLK_MASK,
        RCTRL = Scancode.RCTRL | SDL.SDLK_MASK,
        RSHIFT = Scancode.RSHIFT | SDL.SDLK_MASK,
        RALT = Scancode.RALT | SDL.SDLK_MASK,
        RGUI = Scancode.RGUI | SDL.SDLK_MASK,

        MODE = Scancode.MODE | SDL.SDLK_MASK,

        AUDIONEXT = Scancode.AUDIONEXT | SDL.SDLK_MASK,
        AUDIOPREV = Scancode.AUDIOPREV | SDL.SDLK_MASK,
        AUDIOSTOP = Scancode.AUDIOSTOP | SDL.SDLK_MASK,
        AUDIOPLAY = Scancode.AUDIOPLAY | SDL.SDLK_MASK,
        AUDIOMUTE = Scancode.AUDIOMUTE | SDL.SDLK_MASK,
        MEDIASELECT = Scancode.MEDIASELECT | SDL.SDLK_MASK,
        WWW = Scancode.WWW | SDL.SDLK_MASK,
        MAIL = Scancode.MAIL | SDL.SDLK_MASK,
        CALCULATOR = Scancode.CALCULATOR | SDL.SDLK_MASK,
        COMPUTER = Scancode.COMPUTER | SDL.SDLK_MASK,
        AC_SEARCH = Scancode.AC_SEARCH | SDL.SDLK_MASK,
        AC_HOME = Scancode.AC_HOME | SDL.SDLK_MASK,
        AC_BACK = Scancode.AC_BACK | SDL.SDLK_MASK,
        AC_FORWARD = Scancode.AC_FORWARD | SDL.SDLK_MASK,
        AC_STOP = Scancode.AC_STOP | SDL.SDLK_MASK,
        AC_REFRESH = Scancode.AC_REFRESH | SDL.SDLK_MASK,
        AC_BOOKMARKS = Scancode.AC_BOOKMARKS | SDL.SDLK_MASK,

        BRIGHTNESSDOWN = Scancode.BRIGHTNESSDOWN | SDL.SDLK_MASK,
        BRIGHTNESSUP = Scancode.BRIGHTNESSUP | SDL.SDLK_MASK,
        DISPLAYSWITCH = Scancode.DISPLAYSWITCH | SDL.SDLK_MASK,
        KBDILLUMTOGGLE = Scancode.KBDILLUMTOGGLE | SDL.SDLK_MASK,
        KBDILLUMDOWN = Scancode.KBDILLUMDOWN | SDL.SDLK_MASK,
        KBDILLUMUP = Scancode.KBDILLUMUP | SDL.SDLK_MASK,
        EJECT = Scancode.EJECT | SDL.SDLK_MASK,
        SLEEP = Scancode.SLEEP | SDL.SDLK_MASK,
        APP1 = Scancode.APP1 | SDL.SDLK_MASK,
        APP2 = Scancode.APP2 | SDL.SDLK_MASK,

        AUDIOREWIND = Scancode.AUDIOREWIND | SDL.SDLK_MASK,
        AUDIOFASTFORWARD = Scancode.AUDIOFASTFORWARD | SDL.SDLK_MASK
    }

    [Flags]
    public enum KeyModifier : ushort
    {
        None = 0x0000,
        LeftShift = 0x0001,
        RightShift = 0x0002,
        LeftCtrl = 0x0040,
        RightCtrl = 0x0080,
        LeftAlt = 0x0100,
        RightAlt = 0x0200,
        LeftGui = 0x0400,
        RightGui = 0x0800,
        Num = 0x1000,
        Caps = 0x2000,
        Mode = 0x4000,
        Reserved = 0x8000,

        Ctrl = LeftCtrl | RightCtrl,
        Shift = LeftShift | RightShift,
        Alt = LeftAlt | RightAlt,
        Gui = LeftGui | RightGui
    }
}
